a = input('Digite algo: ')
print('O tipo primitivo deste valor é, ', type(a))
print('Só tem espaços:', a.isspace())
print('É númerico? ', a.isnumeric())
print('É alfanúmerico? ', a.isalnum())
print('É alfabético? ', a.isalpha())
print('Está em maiusculas? ', a.isupper())
print('Está em minúsculas? ', a.islower())
print('Está capitalizada? ', a.istitle())
